### ISSUE TITLE
multi-cs.jsou taken from vendor directory instead of root

### ISSUE THREAD

**Issue by jindrapetrik** [Symplify/MultiCodingStandard#16]
When installed using composer to vendor directory (`vendor\symplify\multi-coding-standard`),
and run via
`vendor\bin\multi-cs.bat src`     on Windows
it uses multi-cs.json file stored in
`\vendor\symplify\multi-coding-standard\multi-cs.json`
instead of
`\multi-cs.json`

**Comment by TomasVotruba** [comment]
I was wondering, could you send PR for that?

**Comment by jindrapetrik** [comment]
I think I could fix it sometimes. But problem is  - I don't understand the relation between vendor dir and src dir - how these things work in composer. If the real app was developed in src directory and then is used in composer which places it to vendor directory. I don't know where to get correct dir - I can google some solutions or how to solve it. This is the reason I did not create PR and just write issue - because I thought you can do it faster.

I said to you (on meeting in our company) thatI fixed it myself by copying the json file to correct directory.
I just created another batch file (bin/cs.bat) in our project, which copies /multi-cs.json into vendor/symplify.../multi-cs.json  and then executes multi-cs.bat in vendor directory and passes all its arguments to it. I think this "solution" works for my current project and is not applicable generally to your bundle.

I already did some investigation about the directories used in your app in the past, but all manual changes I did to the code looked like definitely "not clean" solution so I abandoned the idea to fix it myself.

I can take a look later whether I can figure out something (when I am less tired from my job) and try it... but can't promise anything.

**Comment by TomasVotruba** [comment]
I know this might be bit complex. I've prepared a PR to fix and tested it. Works fine.

Check it, you can learn a lot about my thinking there :) First I created complex solution to check all the paths where it might be, using relative path to `%appDir%` and resolving the value. 

(That's the first commit.)

When I tried to explain it here I realized, I could simply use `getcwd();`, which returns current working directory. So will always load `multi-cs.json` from the directory, where it is used.

(That's the last commit.)

**Comment by TomasVotruba** [comment]
Should be fixed. Released version `v1.0.1`

**Comment by jindrapetrik** [comment]
Looks working to me. Thanks a lot for the fix and explanation!

**Comment by TomasVotruba** [comment]
Glad to help!
